services:
  - type: web
    name: rayan-portfolio
    env: node
    plan: free # or "starter" depending on your tier
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: GITHUB_USER
        value: Rayan-141
      - key: GITHUB_TOKEN
        sync: false # You will add this manually in Render dashboard
      - key: NODE_VERSION
        value: 20
